services:
  - type: web
    name: studyai-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install --legacy-peer-deps --include=dev && npx prisma@6.19.3 db push --accept-data-loss && npx prisma@6.19.3 generate && npx nest build
    startCommand: cd backend && node dist/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_2anZNrvm7WRs@ep-small-smoke-attwr3r0-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: DIRECT_URL
        value: "postgresql://neondb_owner:npg_2anZNrvm7WRs@ep-small-smoke-attwr3r0.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: JWT_SECRET
        value: "a7189c6a7363b674e39e8704460ec6baf4945cfe909025e0bf9f798cef68af336b28e42819d985356bff25f23ed87b6d8df688b02d59df49a513b9fa2516f9fb"
      - key: JWT_EXPIRATION
        value: 7d
      - key: CORS_ORIGINS
        value: "https://studyai-fawn.vercel.app,http://localhost:3000"
      - key: PORT
        value: 4000
      - key: GEMINI_API_KEY
        value: ""
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 60
